language: objective-c
osx_image: xcode9.3

script:
  - set -o pipefail && xcodebuild -project "UIImageView+Extension Demo.xcodeproj" -scheme "UIImageView+Extension Demo" -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO | xcpretty -c 
